In [2]:
import numpy as np

In [3]:
np.set_printoptions(suppress=True) # Si hay un numero muy cercano a cero, solo muestre un cero

In [4]:
A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [7]:
b = np.array([[1],[1]])

In [8]:
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [9]:
x = inversa_A.dot(b)
print(x)

[[0.]
 [1.]]


In [10]:
print(A.dot(x))

[[1.]
 [1.]]


In [11]:
sol_2 = inversa_A.dot(np.array([[3],[7]]))
print(sol_2)

[[-4.]
 [15.]]


In [12]:
print(A.dot(sol_2))

[[3.]
 [7.]]
