In [7]:
import numpy as np

In [12]:
escalar = 5.679
vector= np.array([2,3])
matriz = np.array([[1,2],[3,4],[5,6]])

In [14]:
A = matriz * vector

In [18]:
B = matriz.dot(vector) # .dot es la instruccion para el producto interno

In [19]:
print(A)

[[ 2  6]
 [ 6 12]
 [10 18]]


In [20]:
print(B)

[ 8 18 28]


In [21]:
B = matriz.dot(vector)
C = np.dot(matriz, vector)
print(B)
print(C)

[ 8 18 28]
[ 8 18 28]


In [22]:
E = vector * matriz
print(E)

[[ 2  6]
 [ 6 12]
 [10 18]]
