# 4. Producto Interno

El *producto interno* (estándar) o simplemente *producto punto* de dos $n$-vectores $\vec{a},\vec{b}$ se define como el escalar:

$$
<\vec{a},\vec{b}> = \vec{a} \cdot \vec{b} = a_{0}b_{0}+a_{1}b_{1}+\cdots+a_{n-1}b_{n-1} = \displaystyle\sum_{i=0}^{n-1} a_{i}b_{i}
$$

Que es simplemente la suma del producto de sus entradas.

Por ejemplo, si $\vec{a}=(1,2,3)$ y $\vec{b}=(4,5,6)$ entonces el producto punto será:

$$
\vec{a}\cdot\vec{b} = (1,2,3)\cdot (4,5,6) = 1\cdot 4+2\cdot 5 + 3\cdot 6 = 4+10+18=32
$$

Hasta ahora trabajamos de forma indiferente con *vectores columna* y *vectores renglón*, a partir de este momento **el estándar serán los vectores columna** entonces simpre que hablemos de un vector, dígamos $\vec{a}$ entonces estaremos hablando del vector columna:

$$
\vec{a} = \begin{bmatrix}a_{0}\\ a_{1}\\ \vdots \\ a_{n-1}\end{bmatrix}
$$

Esto también nos permite introducir una nueva operación: **la transposición**. Retomemos el vector $\vec{a}$, denotaremos como $\vec{a}^{T}$ al vector transpuesto de $\vec{a}$:

$$
\vec{a}^{T} = \begin{bmatrix}a_{0}\\ a_{1}\\ \vdots \\ a_{n-1}\end{bmatrix}^{T} = [a_{0}\; a_{1}\; \cdots \; a_{n-1}]
$$

La operación de transposición nos permite cambiar de vectores columna a vectores renglón sin modificar al vector que se transponga. Notemos que es posible poder transponer un vector transpuesto_

$$
\left(\vec{a}^{T}\right)^{T} = \left(\begin{bmatrix}a_{0}\\ a_{1}\\ \vdots \\ a_{n-1}\end{bmatrix}^{T}\right)^{T} = [a_{0}\; a_{1}\; \cdots \; a_{n-1}]^{T} = \begin{bmatrix}a_{0}\\ a_{1}\\ \vdots \\ a_{n-1}\end{bmatrix} = \vec{a}
$$

Así pues, consideremos el ejemplo anterior de los vectores $\vec{a}$ y $\vec{b}$. Definimos la operación $\vec{a}^{T}\vec{b}$ como:

$$
\vec{a}^{T}\; \vec{b} = [a_{0}\; a_{1}\; \cdots \; a_{n-1}]  \begin{bmatrix}b_{0}\\ b_{1}\\ \vdots \\ b_{n-1}\end{bmatrix} = a_{0}b_{0} + a_{1}b_{1} + \cdots + a_{n-1}b_{n-1} = \displaystyle\sum_{i=0}^{n-1} a_{i}b_{i}
$$

Lo cual coincide con la definición del producto interno. Así pues $<\vec{a},\vec{b}> = \vec{a}\cdot \vec{b} = \vec{a}^{T} \;\vec{b} = \displaystyle\sum_{i=0}^{n-1} a_{i}b_{i}$

## 4.1 Propiedades del producto interno

Sean $\vec{a},\vec{b}$ dos $n$-vectores y $\alpha$ un escalar. El producto interno entre $\vec{a}$ y $\vec{b}$ cumple las siguientes propiedades:

* Conmutatividad: $\vec{a}^{T}\vec{b} = \displaystyle\sum_{i=0}^{n-1} a_{i}b_{i} = \displaystyle\sum_{i=0}^{n-1} b_{i}a_{i} = \vec{b}^{T}\vec{a}$

* Asociatividad con multiplicación escalar: $\left(\alpha \vec{a}\right)^{T}\vec{b} = \alpha\left(\vec{a}^{T}\vec{b}\right)$

* Distribución en la adición de vectores: $\left(\vec{a} + \vec{b}\right)^{T}\vec{c} = \vec{a}^{T}\vec{c} + \vec{b}^{T}\vec{c}$

## 4.2 Consideraciones adicionales

**Proyección**. Si $\vec{a}$ es un $n$-vector entonces $\hat{e}_{i}^{T}\vec{a} = a_{i}$

**Suma de elementos de un vector.** $\mathbf{1}^{T}a = a_{0}+a_{1}+\cdots+a_{n-1}$ 

**Promedio de entradas de un vector.** $(\mathbf{1}/n)^{T}\vec{a} = (a_{0}+a_{1}+\cdots+a_{n-1})/n$

**Suma de cuadrados de un vector.** $\vec{a}^{T} \;\vec{a} = a_{0}^{2}+a_{1}^{2}+\cdots+a_{n-1}^{2}$

**Producto interno de bloques de vectores**. Sean $\vec{a},\vec{b}$ $k$-vectores formados por concatenar los $n$-vectores $a_{i},b_{i}$:

$$
\vec{a}=\begin{bmatrix}a_{0}\\ a_{1}\\ \vdots \\ a_{k-1}\end{bmatrix},\qquad \vec{b}=\begin{bmatrix}b_{0}\\ b_{1}\\ \vdots \\ b_{k-1}\end{bmatrix}
$$

Entonces el producto punto entre estos vectores va como:

$$
\vec{a}^{T} \vec{b} = [a_{0}\; a_{1}\; \cdots \; a_{k-1}]\begin{bmatrix}b_{0}\\ b_{1}\\ \vdots \\ b_{k-1}\end{bmatrix} = a_{0}^{T}b_{0}+a_{1}^{T}b_{1} + \cdots + a_{k-1}^{T}b_{k-1}
$$

## 4.3 Producto interno en Python. 

In [1]:
import numpy as np

Sean $\vec{a},\vec{b}$ vectores en $\mathbb{R}^{4}$. Diremos que los vectores son **ortogonales** o **perpendiculares** si $\vec{a}\cdot \vec{b}= 0$

Consideremos entonces $\vec{a}=\hat{e}_{0}$ y $\vec{b} = \hat{e}_{2}$. Vamos a realizar el producto punto en Python

In [2]:
a = np.array([1,0,0,0]) #declaramos el vector e_1

b = np.array([0,0,1,0]) #declaramos el vector e_2

Para realizar el producto punto llamaremos a la función *numpy.dot*

In [3]:
print('<a,b> =',np.dot(a,b))

<a,b> = 0


De igual manera también podemos usar el operador $@$

In [21]:
print('<a,b> =',a.T@b)

<a,b> = 0


**Evaluación de polinomios**. Un polinomio de grado $n-1$ se puede expresar como $p(x) = c_{0} + c_{1}x + c_{2}x^{2} + \cdots + c_{n-1}x^{n-1}$. Si consideramos los $n$-vectores $\vec{c},\vec{x}$ tales que:

$$
\vec{c} = \begin{bmatrix}c_{0}\\ c_{1}\\ \vdots \\ c_{n-1}\end{bmatrix},\qquad \vec{x}(x) = \begin{bmatrix}x^{0}\\ x^{1}\\ \vdots \\ x^{n-1}\end{bmatrix}
$$

Así pues, usando estos vectores es posible expresar $p(x) = \vec{c}^{T}\vec{x}(x)$. Un ejemplo más concreto sería $p(x)=1+2x$, usando los vectores:

$$
\vec{c} = \begin{bmatrix}1\\ 2 \end{bmatrix}, \qquad \vec{x}(x) = \begin{bmatrix}1\\ x \end{bmatrix}
$$

Entonces podemos escribir:
$$
p(x) = \vec{c}^{T}\vec{x}(x) = [1 \; 2] \begin{bmatrix}1\\ x \end{bmatrix} = 1\cdot 1 + 2\cdot x = 1 + 2x
$$

Así pues en Python podemos escribir el polinomio como:

In [2]:
def p(x):
    return np.array([1,2])@np.array([1,x])

In [5]:
print('p(0) = ',p(0))
print('p(1) = ',p(1))
print('p(2) = ',p(2))

p(0) =  1
p(1) =  3
p(2) =  5


## 4.4 Ejercicios.

**Problema 1: Análisis de sentimientos de tweets.** Vamos a crear un máquina que pueda decirnos qué tan positivo, neutral o negativo son una serie de respuestas de twitter.  
Las respuestas son:
> Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!

> Vaya señora que bueno que se asesora por alguien inteligente no por el ignorante del Gatt.

> Se me ocurre y sin ver todos los videos de Plazti que me informéis por dónde empiezo. Entiendo que os tendría que decir quién soy y que quiero, vamos conocerme para asesorarme bien.
Un saludo

> Soy docente universitario, estoy intentando preparar mis clases en modo platzi bien didáctico, (le llamo modo noticiero), descargue una plataforma gratuita de grabación y transmisión de vídeo, se llama Obs estudio!bueno la sigo remando con sus funciones pero sé que saldrá algo!

In [1]:
a = "Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!"
a = a.replace("!","").replace(",","").split(" ")

In [ ]:
** split parte el enunciado en este caso lo parte usando los espacios, crea un vector con la palabras.

In [8]:
a

['Gran',
 'mexicano',
 'y',
 'excelente',
 'en',
 'su',
 'área',
 'su',
 'muerte',
 'es',
 'una',
 'enorme',
 'perdida',
 'y',
 'debería',
 'ser',
 'luto',
 'nacional']

In [2]:
if 'muerte' in a:
    print("Sí")

Sí


Ahora bien, no podemos sacar toda la información de los textos sino vamos a buscar cadenas (strings) específicas. Así pues vamos a construir una función de Python que cuente la cantidad de veces que aparece cierta cadena. Como ejemplo, supongamos que las palabras que vamos a contar son *muerte*, *pérdida*, *luto*, *excelente*,*gran* y *positivo*, y además esto lo queremos expresar como vector en orden respectivo, así pues el primer comentario lo podemos expresar como el siguiente vector:
$$
\vec{w} = \begin{bmatrix}1\\ 1 \\ 1\\ 1\\ 1 \\0 \end{bmatrix}
$$
Ahora, vamos a crear otra función en la que tendremos el vector con entradas de cantidad de palabras positivas, negativas y neutras. Siguiendo con el ejemplo vamos a sumar un uno a la primer entrada si aparece alguna de las siguientes palabras *excelente*,*gran* y *positivo*, un uno en la segunda por cada vez que aparezca la palabra *pérdida* y un uno a la última entrada si aparecen las palabras *muerte* y *luto*. Así pues, el primer twett lo podemos representar como:

$$
\vec{s} = \begin{bmatrix} 2 \\ 1 \\2 \end{bmatrix}
$$

Ahora, para ver la *calidad* del resultado que tendremos para un twett conviene calcular el promedio de las entradas de un vector de palabras
$$avg(\vec{w}) = (\mathbf{1}/n)^{T}\vec{w}$$
Y después calcularás el promedio del sentimiento de cada tweet $avg(\vec{s})$ y de igual manera el *score sentimental* que se define como 
$$score(\vec{s}) = [1\; 0\; -1] \begin{bmatrix} s_{0} \\ s_{1} \\s_{2} \end{bmatrix}$$

Leyendo los tuits decide el conjunto mínimo de palabras que vas a contar en todos los tuits, solamente deberás hacer una función para contar palabras para todos los tuits, no hagas un función por enunciado. Según tu esquema reponde lo siguiente:

* ¿Qué tuit es más positivo?

* ¿Qué tuit es más negativo?

* ¿Cuál es tu calidad promedio?

* ¿Cómo interpretas $avg(\vec{s})$ y $score(\vec{s})$?

* ¿Cómo relacionas la calidad con $score(\vec{s})$ y $avg(\vec{s})$?

In [45]:
import numpy as np

class Twit:
    positivos = ['bien', 'bueno', 'excelente', 'inteligente', 'intentando', 'quiero', 'saldrá', 'sigo', 'vamos', 'gran']
    neutrales = ['entiendo', 'plazti', 'alguien', 'asesora', 'asesorarme', 'clases', 'conocerme', 'debería', 'decir', 'descargue',
                 'didáctico', 'docente', 'dónde', 'empiezo', 'enorme', 'funciones', 'grabación', 'gratuita', 'informéis', 'llama',
                 'llamo', 'mexicano', 'nacional', 'noticiero', 'ocurre', 'plataforma', 'preparar', 'remando', 'saludo', 'señora', 'tendría',
                 'todos', 'transmisión', 'universitario', 'ver', 'videos', 'vídeo', 'área']
    negativas = ['ignorante', 'luto', 'muerte', 'perdida']
    words_specials = positivos + neutrales + negativas

    def __init__(self, string):
        self.string = string
        self.string_split = None
        self.w = np.zeros(len(self.words_specials)).reshape(-1, 1)
        self.s = np.zeros(3).reshape(-1, 1)
        self.avg = None
        self.score = None

    def fit(self):
        self.string_split = self.string.lower()
        self.string_split = self.string_split.replace('!', '').replace(',', '').replace('.', '').replace('(', '').replace(')', '').split()
        self.string_split = np.asarray(self.string_split)

        words, times = np.unique(self.string_split, return_counts=True)
        for i, j in enumerate(self.words_specials):
            if j in words:
                index = np.where(words == j)
                self.w[i] = times[index]

        for i in self.string_split:
            if i in self.positivos:
                self.s[0] += 1
            elif i in self.negativas:
                self.s[2] += 1
            elif i in self.neutrales:
                self.s[1] += 1

        self.avg = (np.ones(len(self.w)).reshape(-1, 1) / len(self.w)).T.dot(self.w)
        self.score = np.array([1, 0, -1]).dot(self.s)

    def print_result(self):
        print(f'El twit: {self.string}')
        print(f'Tiene una suma w de: {int(sum(self.w))}')
        print(f'Una s de:\n{self.s}')
        print(f'Un avg de: {float(self.avg)}')
        print(f'Un score de: {int(self.score)}')

a = 'Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!'
b = 'Vaya señora que bueno que se asesora por alguien inteligente no por el ignorante del Gatt.'
c = 'Se me ocurre y sin ver todos los videos de Plazti que me informéis por dónde empiezo.'
d = 'Soy docente universitario, estoy intentando preparar mis clases en modo platzi bien didáctico, (le llamo modo noticiero), descargue una plataforma gratuita de grabación y transmisión de vídeo, se llama Obs estudio!bueno la sigo remando con sus funciones pero sé que saldrá algo!'

In [47]:
a = Twit(a)
a.fit()
a.print_result()

b = Twit(b)
b.fit()
b.print_result()

c = Twit(c)
c.fit()
c.print_result()

d = Twit(d)
d.fit()
d.print_result()

El twit: Gran mexicano y excelente en su área, su muerte es una enorme perdida y debería ser luto nacional!!!
Tiene una suma w de: 10
Una s de:
[[2.]
 [5.]
 [3.]]
Un avg de: 0.19230769230769232
Un score de: -1
El twit: Vaya señora que bueno que se asesora por alguien inteligente no por el ignorante del Gatt.
Tiene una suma w de: 6
Una s de:
[[2.]
 [3.]
 [1.]]
Un avg de: 0.11538461538461539
Un score de: 1
El twit: Se me ocurre y sin ver todos los videos de Plazti que me informéis por dónde empiezo.
Tiene una suma w de: 8
Una s de:
[[0.]
 [8.]
 [0.]]
Un avg de: 0.15384615384615385
Un score de: 0
El twit: Soy docente universitario, estoy intentando preparar mis clases en modo platzi bien didáctico, (le llamo modo noticiero), descargue una plataforma gratuita de grabación y transmisión de vídeo, se llama Obs estudio!bueno la sigo remando con sus funciones pero sé que saldrá algo!
Tiene una suma w de: 20
Una s de:
[[ 4.]
 [16.]
 [ 0.]]
Un avg de: 0.38461538461538464
Un score de: 4
